// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy_EQTXMWBML9le3xtO3W0fYH58aAWHeQ',
    appId: '1:856068824549:web:9fbb79d7f1ca14ecbf630c',
    messagingSenderId: '856068824549',
    projectId: 'fashion-store-mobile-app-3ed1f',
    authDomain: 'fashion-store-mobile-app-3ed1f.firebaseapp.com',
    storageBucket: 'fashion-store-mobile-app-3ed1f.firebasestorage.app',
    measurementId: 'G-CESYY33KQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLg8B3pKr6Bbt_ZtJmWqUIMgJs-UFDa4w',
    appId: '1:856068824549:android:5ab76cd791cdf6fabf630c',
    messagingSenderId: '856068824549',
    projectId: 'fashion-store-mobile-app-3ed1f',
    storageBucket: 'fashion-store-mobile-app-3ed1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNiBOgSjOOCikXoyYHbwx3sXJ8SDNdl0M',
    appId: '1:856068824549:ios:ef5a9f08582edd83bf630c',
    messagingSenderId: '856068824549',
    projectId: 'fashion-store-mobile-app-3ed1f',
    storageBucket: 'fashion-store-mobile-app-3ed1f.firebasestorage.app',
    iosBundleId: 'com.example.stylehubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNiBOgSjOOCikXoyYHbwx3sXJ8SDNdl0M',
    appId: '1:856068824549:ios:ef5a9f08582edd83bf630c',
    messagingSenderId: '856068824549',
    projectId: 'fashion-store-mobile-app-3ed1f',
    storageBucket: 'fashion-store-mobile-app-3ed1f.firebasestorage.app',
    iosBundleId: 'com.example.stylehubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy_EQTXMWBML9le3xtO3W0fYH58aAWHeQ',
    appId: '1:856068824549:web:4e80d1d5a8f006aebf630c',
    messagingSenderId: '856068824549',
    projectId: 'fashion-store-mobile-app-3ed1f',
    authDomain: 'fashion-store-mobile-app-3ed1f.firebaseapp.com',
    storageBucket: 'fashion-store-mobile-app-3ed1f.firebasestorage.app',
    measurementId: 'G-VT1KEG4T99',
  );
}
